### Zwei gegen Zwei mit 3 Bällen

Die Übung wird auf dem halben halben Feld gespielt. Jedes 2er-Team hat einen eigenen Ball (**Teamball**), und ein dritter Ball (**Spielball**) wird mit den üblichen drei Berührungen wie im regulären Volleyball ausgespielt. Die Herausforderung besteht darin, dass kein Ball den Boden berühren darf.

Der **Teamball** darf weder abgelegt noch fallengelassen werden. Er kann entweder zwischen den Teammitgliedern zugespielt oder selbst hochgeworfen werden, muss aber stets in der Luft bleiben. Für den **Spielball** gelten die regulären Volleyballregeln, allerdings muss der Ball immer auf die Person in der gegenerischen Mannschaft gespielt werden die keinen Ball hält. Berührt einer der beiden Bälle den Boden oder wird ein anderer Fehler gemacht, zählt der Punkt als verloren. Das Team, das den Fehler begangen hat, wird durch das nächste wartende Team ersetzt.

:::{.callout-tip}
## Varianten

- Jede Person hält einen Ball in der Hand.
- Der Ball darf auch auf die Person gespielt werden, die den Ball in der Hand hält.
- 3 gegen 3 mit 5 oder 7 Bällen. 
:::

{{< video https://www.youtube.com/embed/5yaXifUSr9s?start=200 >}}
