### Abwehr – Zuspiel – Angriff  

Zwei Dreiergruppen: Eine Gruppe steht am Netz mit einer Person auf Position **2** und zwei auf Position **4**. Eine **abwehrende Person** steht auf Position **1**. Der Rest hinter dem Feld.  

Die Übung beginnt mit einem Angriff von **4** auf **1**. Der Angriff wird abgewehrt, und die **angreifende Person** wird zur **zuspielenden Person**. Diese spielt von **2,5** auf **2** zu und stellt sich dann hinter **2** an. Die **abwehrende Person** stellt sich hinter **6** an, während eine neue **abwehrende Person** auf **5** läuft und den nächsten Angriff von **2** erwartet.  

Der zugespielte Ball wird von **2** angegriffen und von **5** abgewehrt. Die Person auf **2** wird nun die neue **zuspielende Person** und spielt von **2,5** auf **4** zu. Die **abwehrende Person** von **5** stellt sich wieder hinten an, und eine neue **abwehrende Person** läuft auf Position **1**, um zu verteidigen. Ab hier beginnt die Abfolge von vorn.  

Drei **Spielende** wechseln sich auf der Netzposition ab und greifen diagonal an.  
Drei **Spielende** wechseln sich in der Abwehr ab (auf Position **1** und **5**).  

:::{.callout-important}  
## Übungsziele  
- Ballkontrolle  
- Richtige Position zum Ball in der Abwehr  
- Richtige [Abwehrposition](/tech/defense-ready.qmd)  
:::  

:::{.callout-tip}
## Varianten 
- Auch mit zwei **abwehrenden Personen** möglich  
- Angriff im Sprung  
- Longline-Angriff  
:::


{{< video https://www.youtube.com/embed/S3h2N2F7bqI >}}
