### Diagonalspiel

Auf beiden Feldhälften wird eine Mannschaft mit mindestens drei Personen aufgestellt. Benötigt wird eine zuspielende Person auf Position **2**, eine angreifende Person auf Position **4** und eine abwehrende Person auf Position **5**. Der Ball wird durch Einwerfen ins Spiel gebracht. Danach wird der Ball ausgespielt und (leicht) diagonal angegriffen. Nachdem der Ball das Netz überquert hat, rotiert die Mannschaft eine Position weiter. Auf der anderen Feldhälfte wird der Ball ebenfalls ausgespielt, diagonal angegriffen und anschließend eine Position weiter rotiert. Nach einem Fehler wird der Ball möglichst schnell wieder ins Spiel gebracht. Falls mehr Personen vorhanden sind, werden weitere Positionen aufgefüllt, beginnend mit Position **6**.

:::{.callout-tip}
## Varianten
- Die angreifende Person auf Position **4** beginnt in Blockposition am Netz und zieht sich erst beim Zuspiel zurück.  
- Die Richtung wird gewechselt.  
- Alle sichern den Angriff ab.  
- Die zuspielende Person versucht zu blocken, um die Angriffssicherung zu testen.  
:::  
