### Schöne Annahmen


### Aufschlag – Annahme – Zuspiel  

Mindestens eine **Dreiergruppe**: Eine **annahmende Person**, eine **zuspielende/fangende Person** und eine oder mehrere **aufschlagende Personen**.  

Die **aufschlagenden Personen** führen Aufschläge auf die **annahmende Person** aus, die den Ball zur **fangenden Person** annimmt. Diese zählt die gelungenen Annahmen. Nach einer festgelegten Anzahl guter Annahmen wird gewechselt. Die Übung kann auf mehreren Feldhälften oder -dritteln parallel durchgeführt werden.  

:::{.callout-tip}  
## Varianten  
- Nach jedem Ballwechsel wird die Position getauscht (dem Ball nachlaufen).  
- Die ersten **x** Aufschläge sind leicht und müssen im oberen Zuspiel angenommen werden.  
- Falls mehrere **aufschlagende Personen** pro Gruppe vorhanden sind, können die letzten Aufschläge mit mehr Risiko gespielt werden (Wartezeit beachten).  
- Bei zwei Gruppen können die Aufschläge auch diagonal erfolgen.  
- Alternativ kann diagonal dem Ball nachgelaufen werden.  
- Aufschläge werden von einem niedrigen Kasten ausgeführt, um härtere Aufschläge zu simulieren.  
:::
