### Aufschlag-Annahme-Angriff-Abwehr

In Feldhälfte **A** werden folgende Positionen besetzt:

- Zuspiel
- Annahme (2X)
- Angriff
- Warteposition

In Feldhälfte **B** werden folgende Positionen besetzt:

- Abwehr (diagonal)
- Aufschlag
- Warteposition

Bis auf den Zuspieler in Feldhälfte **A** rotieren alle Spieler nach jedem Ball eine Position weiter. (Grob folgt man immer dem Ball)

Der Ablauf ist wie folgt:

1. Aufschlag über das Netz in Feldhälfte **A** (auf die Annahmepositionen)
2. Annahme zum Zuspiel
3. Zuspiel auf die angreifende Person (Position und Art des Zuspiels vorher festlegen)
4. Angriff auf die abwehrende Person
5. Abwehr zu sich selbst und den Ball fangen
6. Alle rotieren eine Position weiter und wieder Aufschlag

Es können bei dieser Übung diverse Sachen geübt werden:

:::{.callout-important}
## Übungsschwerpunkte
- Zuspiel (mit laufen)
- Technik Angriff
- Annahme und Abstimmung zu zweit
- Abwehr (frühzeitiges erkennen der Schlagrichtung und Positionierung zum Angriff)
- Abwehrtechnik
:::

:::{.callout-tip}
## Varianten
- Verschiedene Angriffsoptionen (Aussen Mitte über Kopf)
- Die zuspielende Person läuft von Position 1, oder 4/5
- Annehmende Spieler:innen gehen zur Angriffssicherung
- Zusätzliche Spielende können noch z.B. 
  - einen Block stellen (1-2 Spieler)
  - zusätzliche Abwehrspielende
  - zusätzlicher Annahmespielende
  - etc..
:::
