---
title: Annahme/Abwehr
lang: de
---

## Technik

{{< include tech/defense-ready.qmd >}}

{{< include tech/defense-move.qmd >}}

{{< include tech/defense-arms.qmd >}}

{{< include tech/defense-ball.qmd >}}

{{< include tech/defense-drop-step.qmd >}}

## Übungen

{{< include drills/nice-reception.qmd >}}

{{< include drills/fast-legs.qmd >}}

{{< include drills/reception-action.qmd >}}

## Abwehr

{{< video https://www.youtube.com/embed/U2fTX-e-B6c?si=B8LkeYCoGldu2LGC >}}

### Sichern

{{< video https://www.youtube.com/embed/dLQIOUDR4NM?si=i8CVIKox9qnGNK_H >}}

### Abwehr Ausdauerdrill

Auf einer Feldhälfte steht jeweils ein Spieler auf Position **2** und **4** und auf der anderen Seite des Netzes ein Spieler auf Position **3**. Jeder der Spieler hat 2 Bälle. Der Abwehrspieler beginnt auf Position **1** und wehrt einen geschlagenen Ball von Position **4** ab. Danach wir ein Ball von Postion **3** gelegt ein Ball von Position **2** angegriffen wieder ein Ball von Position **3** gelegt, danach ein Angriff von Position **4** abgewehrt und ein gelegter Ball von Position **2** abgewehrt. Es können beide Feldhälften genutzt werden.

:::{.callout-tip} 
## Varianten
* Alle geschlagenen Bälle können auch gelegt werden
:::

{{< video https://www.youtube.com/embed/oMHZulZ7zg0?si=0tyU89PIfMNXHtIg >}}

### Abwehr hoch Feldmitte

Je ein Angreifer auf **2** und **4**. 1 Ball. Mindestens 3 Spieler in Warteposition hinter dem Feld. Ein Spieler beginnt und spielt den Ball zu dem ihm diagonal stehenden Angreifer, dieser greift an und der Spieler wehrt hoch in die Feldmitte ab. Spieler verlässt das Feld. Ein neuer Spieler von der Warteposition läuft ein und spielt den Ball zum anderen Angreifer, der wiederum auf den neuen Spieler angreift. Dieser wehrt wieder hoch ab und verlässt das Feld und ein neuer Spieler läuft ein...

:::{.callout-important}
## Übungsziel
- Abwehr nicht zum Angreifer, sondern hoch in die Feldmitte.
:::

### Abwehrvariation

Es werden 3 Spielende mit 2 Bällen benötigt. Eine abwehrende Person steht auf der seitlichen Aus-Linie, eine angreifende Person auf gegenüberliegenden Linie, die zweite angreifende Person ca. in der Mitte. Es erfolgen 2 Angriffe auf den Abwehrspieler. Einmal hart und fest aus der Mitte und einmal eher als Float-/Driveschlag von der weiter entfernten Person. Beide Bälle werden zur Person in der Mitte angenommen.

:::{.callout-important}
## Übungsziel

- Darauf achten, dass beim harten Angriff die Kraft eher aus dem Ball genommen wird und beim Float-/Driveangriff eine aktive Bewegung mit den Armen erfolgt.
:::


### Langer Ball

Am Netz werden auf einer Seite zwei Schlangen gebildet. Der Trainer wirft aus der Mitte einen langen Ball auf die andere Feldhälfte, der jeweils der erste Spieler jeder Schlange läuft auf die andere Hälfte des Feldes. Ein Spieler wehrt den Ball hoch zur Feldmitte ab, der zweite Spieler spielt den Ball (im oberen Zuspiel) lang in eine Ecke der anderen Feldhälfte. Danach holt ein Spieler den Ball und legt ihn beim Trainer ab und stellt sich anschließend hinten an.

:::{.callout-tip} 
## Varianten
* Der zweite Ballkontakt wird als (Rückraum-)Zuspiel ausgeführt und der dritte Kontakt als (Rückraum-)Angriff.
:::

### Abwehr verschieben

{{< video https://www.youtube.com/embed/lL4noI7lHrI?si=xB5Pl-KmMdYG8Auz >}}

### Abwehr & Reaktion

Paarweise. Ein Medizinball o. Ä. wird benutzt um den Ball zu prellen und ihm eine zufällige Richtung zu geben. Der Abwehrspieler muss versuchen den Ball zu erlaufen und (am Besten mit zwei Armen) abzuwehren.


### Dankeball mit laufen

{{< video https://www.youtube.com/embed/pp1D-uoNM3o >}}

### Abwehr zu dritt

Drei Abwehrspieler auf Position **1**, **5** und **6**. Ein Zuspieler/Angreifer am Netz. Der Zuspieler spielt die Bälle lange, kurz oder als Angriff auf die 3 Abwehrspieler, die diesen wiederum hoch zum Zuspieler abwehren, sodass sofort weiter gespielt werden kann.


:::{.callout-tip}
## Varianten
* Nach jedem Ballkontakt eines Spielers auf Position **1** oder **5** wechselt dieser Position mit dem Spieler auf Position **6**.
* Nach jedem kurzen (gelegtem) Ball geht der Spieler der den Ball abgewehrt hat auf die lange **6** und der Spieler auf der **6** rückt auf die Position des Ballspielenden.
:::


{{< video https://www.youtube.com/embed/NEzf3sKM2ZQ >}}


### Abwehr-Kette

An der langen Seite des Feldes stellt sich ca. die Hälfte der Spieler mit jeweils 2 Bällen auf. Zwischen 2 Spieler wird auf der gegenüberliegenden Hälfte ein Hütchen/Medizinball gelegt. Die restliche Spieler laufen nun mit Abstand in Position und wehren 2 Bälle ab und laufen danach hinter dem Hütchen zum nächsten Spieler und wehren wiederum 2 Bälle ab. Auf Abstand zwischen den Spielern achten.

:::{.callout-tip}
## Varianten
* Die Angreifer variieren und streuen gelegte Bälle ein
:::
