### Kreuzschritt

(Bewegung nach rechts beschrieben. Nach links analog) 

- [Grundposition](/tech/defense-ready.qmd)
- rechter Fuß macht einen großen Schritt nach rechts und leicht weg vom Netz. Fuß parallel zum Netz. Körper öffnet sich in Laufrichtung
- linker Fuß wird nachgezogen, am rechten Fuß weit vorbeigeführt und stemmt ein um die Bewegung zu stoppen und den Schwung für den Sprung zu nutzen. Fuß steht möglichst im rechten Winkel zum Netz Körper dreht sich wieder zum Netz
- rechter Fuß wir parallel zum linken Fuß in Schulterbreite nachgeführt und stemmt ebenfalls ein.
- Sprung ohne Seitwärtsbewegung gerade nach oben
- Hände und Arme bleiben die ganze Zeit in gehobener Position um eine Netzberührung zu vermeiden
- (Variante: Swingblock: die Arme zum Schwung holen benutzt und man Versucht die Hände möglichst körpernah nach oben zu schieben um eine Netzberührung zu vermeiden)
- Falls eine seitliche Bewegung nach dem Stemmschritt nicht verhindert werden kann, versuchen mit der Hüfte anzudocken um eine Berührung mit den Füßen zu vermeiden.
